import Link from 'next/link';

export default function Home() {
  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100 flex flex-col">
      {/* Hero Section */}
      <header className="flex-1 flex flex-col items-center justify-center px-6 text-center py-20 bg-gradient-to-b from-zinc-900 to-zinc-950">
        <div className="w-20 h-20 rounded-2xl bg-gradient-to-tr from-zinc-100 to-zinc-400 flex items-center justify-center shadow-2xl mb-8 animate-in fade-in zoom-in duration-700">
          <span className="text-zinc-950 font-black text-3xl">SL</span>
        </div>
        
        <h1 className="text-5xl md:text-7xl font-black tracking-tight mb-4 bg-gradient-to-r from-zinc-100 via-zinc-300 to-zinc-500 bg-clip-text text-transparent">
          SupportLens
        </h1>
        
        <p className="text-lg md:text-2xl text-zinc-400 max-w-2xl mb-10 font-medium">
          The AI-Powered Customer Support Platform for the modern web.
        </p>

        <div className="flex flex-col sm:flex-row gap-4">
          <Link 
            href="/session/test123"
            className="px-8 py-4 bg-zinc-100 hover:bg-zinc-200 text-zinc-950 rounded-2xl font-bold text-lg transition-all shadow-xl hover:scale-105 active:scale-95"
          >
            Start Demo
          </Link>
          <Link 
            href="/dashboard/admin"
            className="px-8 py-4 bg-zinc-900 hover:bg-zinc-800 text-zinc-100 rounded-2xl font-bold text-lg border border-zinc-800 transition-all shadow-xl hover:scale-105 active:scale-95"
          >
            Admin Panel
          </Link>
        </div>
      </header>

      {/* Features Grid */}
      <section className="max-w-6xl mx-auto px-6 py-24 w-full">
        <h2 className="text-xs font-bold text-zinc-500 uppercase tracking-[0.2em] mb-12 text-center">Core Capabilities</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {[
            {
              title: "Video Calling",
              desc: "High-quality WebRTC video powered by Mediasoup SFU.",
              icon: "🎥"
            },
            {
              title: "Real-time Chat",
              desc: "Instant messaging with persistent history and delivery status.",
              icon: "💬"
            },
            {
              title: "File Sharing",
              desc: "Securely upload and share documents or images during calls.",
              icon: "📎"
            },
            {
              title: "AI Summary",
              desc: "Automated session summaries generated by advanced AI.",
              icon: "🤖"
            },
            {
              title: "Session History",
              desc: "Complete logs of all past support interactions and transcripts.",
              icon: "📜"
            },
            {
              title: "Admin Dashboard",
              desc: "Operational overview with real-time metrics and session tracking.",
              icon: "📊"
            }
          ].map((feature, i) => (
            <div 
              key={i} 
              className="p-8 rounded-3xl border border-zinc-900 bg-zinc-900/30 backdrop-blur-sm hover:border-zinc-800 transition-colors group"
            >
              <div className="text-3xl mb-4 group-hover:scale-110 transition-transform inline-block">{feature.icon}</div>
              <h3 className="text-xl font-bold text-zinc-100 mb-2">{feature.title}</h3>
              <p className="text-zinc-500 leading-relaxed text-sm">{feature.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 border-t border-zinc-900 text-center">
        <p className="text-zinc-600 text-sm">© 2026 SupportLens. All rights reserved.</p>
      </footer>
    </div>
  );
}
